//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AchTransaction
    {
        public AchTransaction()
        {
            this.NextRecurringPayments = new HashSet<NextRecurringPayment>();
            this.NextRecurringPayments1 = new HashSet<NextRecurringPayment>();
        }
    
        public long AchTransactionId { get; set; }
        public int BankAccountId { get; set; }
        public bool IsCredit { get; set; }
        public decimal Amount { get; set; }
        public int StatusCode { get; set; }
        public string StatusMessage { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime UpdateDateUtc { get; set; }
        public string ProviderId { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual ICollection<NextRecurringPayment> NextRecurringPayments { get; set; }
        public virtual ICollection<NextRecurringPayment> NextRecurringPayments1 { get; set; }
    }
}
