//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiCustomer
    {
        public ApiCustomer()
        {
            this.ApiCustomerKeys = new HashSet<ApiCustomerKey>();
        }
    
        public int CustomerId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ApiCustomerKey> ApiCustomerKeys { get; set; }
    }
}
