//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiCustomerKey
    {
        public int CustomerId { get; set; }
        public string ApiName { get; set; }
        public System.Guid ApiKey { get; set; }
        public string ConnectionString { get; set; }
    
        public virtual ApiCustomer ApiCustomer { get; set; }
    }
}
