//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public long ApplicationId { get; set; }
        public int UserId { get; set; }
        public long BuildingId { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public string StatusText { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual User User { get; set; }
    }
}
