//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutopaySetting
    {
        public AutopaySetting()
        {
            this.ScheduledTransactions = new HashSet<ScheduledTransaction>();
        }
    
        public long AutopaySettingId { get; set; }
        public int PaymentSeriesId { get; set; }
        public long PaymentMethodId { get; set; }
        public int TenantId { get; set; }
        public bool IncludeFirstPayment { get; set; }
        public Nullable<decimal> FirstPaymentAmount { get; set; }
        public Nullable<System.DateTime> FirstPaymentDateUtc { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime StartDateUtc { get; set; }
        public int PaymentTypeCode { get; set; }
        public int StatusCode { get; set; }
        public string StatusMessage { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime UpdateDateUtc { get; set; }
        public int MonthlyPaymentDay { get; set; }
    
        public virtual Tenant Tenant { get; set; }
        public virtual PaymentSeries PaymentSeries { get; set; }
        public virtual ICollection<ScheduledTransaction> ScheduledTransactions { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
