//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        public BankAccount()
        {
            this.AchTransactions = new HashSet<AchTransaction>();
            this.PaymentInvites = new HashSet<PaymentInvite>();
            this.RecurringPayments = new HashSet<RecurringPayment>();
            this.RecurringPayments1 = new HashSet<RecurringPayment>();
            this.NextRecurringPayments = new HashSet<NextRecurringPayment>();
            this.NextRecurringPayments1 = new HashSet<NextRecurringPayment>();
        }
    
        public int BankAccountId { get; set; }
        public int UserId { get; set; }
        public int TypeCode { get; set; }
        public string AccountNumber { get; set; }
        public string RoutingNumber { get; set; }
        public string CommerceId { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime UpdateDateUtc { get; set; }
        public string Nickname { get; set; }
    
        public virtual ICollection<AchTransaction> AchTransactions { get; set; }
        public virtual ICollection<PaymentInvite> PaymentInvites { get; set; }
        public virtual ICollection<RecurringPayment> RecurringPayments { get; set; }
        public virtual ICollection<RecurringPayment> RecurringPayments1 { get; set; }
        public virtual ICollection<NextRecurringPayment> NextRecurringPayments { get; set; }
        public virtual ICollection<NextRecurringPayment> NextRecurringPayments1 { get; set; }
        public virtual User User { get; set; }
    }
}
