//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public Brand()
        {
            this.BrandServices = new HashSet<BrandService>();
        }
    
        public int BrandId { get; set; }
        public string Name { get; set; }
        public string SiteUrl { get; set; }
        public string Phone { get; set; }
        public string LogoUrl { get; set; }
        public bool IsNational { get; set; }
    
        public virtual ICollection<BrandService> BrandServices { get; set; }
    }
}
