//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandService
    {
        public BrandService()
        {
            this.BrandZips = new HashSet<BrandZip>();
        }
    
        public int BrandServiceId { get; set; }
        public int BrandId { get; set; }
        public string Name { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual ICollection<BrandZip> BrandZips { get; set; }
    }
}
