//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandZip
    {
        public long BrandZipId { get; set; }
        public int BrandServiceId { get; set; }
        public int ZipCode { get; set; }
    
        public virtual BrandService BrandService { get; set; }
    }
}
