//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public Building()
        {
            this.Applications = new HashSet<Application>();
            this.BuildingAmenities = new HashSet<BuildingAmenity>();
            this.BuildingUtilities = new HashSet<BuildingUtility>();
            this.CustomAmenities = new HashSet<CustomAmenity>();
            this.FeaturedListings = new HashSet<FeaturedListing>();
            this.Orders = new HashSet<Order>();
            this.PaymentInvites = new HashSet<PaymentInvite>();
            this.Photos = new HashSet<Photo>();
            this.RecurringPayments = new HashSet<RecurringPayment>();
            this.SavedBuildings = new HashSet<SavedBuilding>();
            this.TenantApplications = new HashSet<TenantApplication>();
            this.NextRecurringPayments = new HashSet<NextRecurringPayment>();
            this.Notifications = new HashSet<Notification>();
            this.RefreshSchedules = new HashSet<RefreshSchedule>();
            this.RentalApplications = new HashSet<RentalApplication>();
            this.ListingReports = new HashSet<ListingReport>();
            this.Threads = new HashSet<Thread>();
        }
    
        public long BuildingId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> CreateDateUtc { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDateUtc { get; set; }
        public string UpdatedBy { get; set; }
        public string RibbonId { get; set; }
        public Nullable<System.DateTime> DateRibbonActivated { get; set; }
        public Nullable<int> ContactInfoId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public float Latitude { get; set; }
        public float Longitude { get; set; }
        public int PropertyTypeCode { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> SquareFeet { get; set; }
        public Nullable<float> Acres { get; set; }
        public Nullable<int> YearBuilt { get; set; }
        public Nullable<int> Bedrooms { get; set; }
        public Nullable<float> Bathrooms { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> DateAvailableUtc { get; set; }
        public Nullable<System.DateTime> DateActivatedUtc { get; set; }
        public bool IsActive { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> RefundableDeposit { get; set; }
        public int LeaseLengthCode { get; set; }
        public bool IsSmokingAllowed { get; set; }
        public bool IsRemovedByAdmin { get; set; }
        public bool IsReported { get; set; }
        public string ReportedText { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<decimal> PetFee { get; set; }
        public Nullable<int> TemporaryOrderId { get; set; }
        public Nullable<System.Guid> PrimaryPhotoId { get; set; }
        public string PrimaryPhotoExtension { get; set; }
        public bool IsUpgraded { get; set; }
        public Nullable<int> TransUnionPropertyId { get; set; }
        public bool IsApplicationsEnabled { get; set; }
        public string StreetHash { get; set; }
        public string FullHash { get; set; }
        public Nullable<bool> IsScreeningRequired { get; set; }
        public string Nickname { get; set; }
        public Nullable<int> ManagementTypeCode { get; set; }
        public string DefaultCity { get; set; }
        public int DogPolicyCode { get; set; }
        public int CatPolicyCode { get; set; }
        public string PetDetails { get; set; }
        public Nullable<decimal> PetDeposit { get; set; }
        public string SmokingDetails { get; set; }
        public bool IsLeaseToOwn { get; set; }
        public bool IsSeniorRestricted { get; set; }
        public Nullable<decimal> ApplicationFee { get; set; }
        public string MoveInSpecial { get; set; }
        public string CustomPhoneId { get; set; }
        public string CustomPhoneNumber { get; set; }
        public bool RecordCalls { get; set; }
        public Nullable<long> CommunityId { get; set; }
        public Nullable<System.Guid> FloorPlanImageId { get; set; }
        public Nullable<bool> AutoRentability { get; set; }
        public string FloorPlanImageExtension { get; set; }
        public string Directions { get; set; }
        public bool IsOnApprovedCredit { get; set; }
        public bool IsMonthToMonth { get; set; }
        public int MinLeaseLength { get; set; }
        public int MaxLeaseLength { get; set; }
        public Nullable<int> IsAcceptTextMessages { get; set; }
        public int OrderScore { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public bool IsDIYApartment { get; set; }
        public string YouTubeUrl { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<BuildingAmenity> BuildingAmenities { get; set; }
        public virtual Community Community { get; set; }
        public virtual Property Property { get; set; }
        public virtual ICollection<BuildingUtility> BuildingUtilities { get; set; }
        public virtual ContactInfo ContactInfo { get; set; }
        public virtual Order Order { get; set; }
        public virtual ICollection<CustomAmenity> CustomAmenities { get; set; }
        public virtual ICollection<FeaturedListing> FeaturedListings { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<PaymentInvite> PaymentInvites { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
        public virtual ICollection<RecurringPayment> RecurringPayments { get; set; }
        public virtual ICollection<SavedBuilding> SavedBuildings { get; set; }
        public virtual ICollection<TenantApplication> TenantApplications { get; set; }
        public virtual ICollection<NextRecurringPayment> NextRecurringPayments { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<RefreshSchedule> RefreshSchedules { get; set; }
        public virtual ICollection<RentalApplication> RentalApplications { get; set; }
        public virtual ICollection<ListingReport> ListingReports { get; set; }
        public virtual ICollection<Thread> Threads { get; set; }
        public virtual User User { get; set; }
    }
}
