//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Community
    {
        public Community()
        {
            this.CommunityAmenities = new HashSet<CommunityAmenity>();
            this.OperatingDays = new HashSet<OperatingDay>();
            this.FeaturedCommunities = new HashSet<FeaturedCommunity>();
            this.CommunityPhotos = new HashSet<CommunityPhoto>();
            this.Buildings = new HashSet<Building>();
        }
    
        public long CommunityId { get; set; }
        public int UserId { get; set; }
        public string Nickname { get; set; }
        public int ManagementTypeCode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string DefaultCity { get; set; }
        public float Latitude { get; set; }
        public float Longitude { get; set; }
        public Nullable<int> TotalUnits { get; set; }
        public bool IsUpgraded { get; set; }
        public string RequestedPackage { get; set; }
        public Nullable<int> AdvertisedListingCount { get; set; }
        public Nullable<int> FeaturedPlacementCount { get; set; }
        public Nullable<int> RefreshDays { get; set; }
        public bool IsUnderReview { get; set; }
        public string InvoiceContactName { get; set; }
        public string InvoiceContactPhone { get; set; }
        public string StreetHash { get; set; }
        public string FullHash { get; set; }
        public Nullable<System.Guid> MainPhotoId { get; set; }
        public string MainPhotoExtension { get; set; }
        public Nullable<System.Guid> HeaderPhotoId { get; set; }
        public string HeaderPhotoExtension { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDateUtc { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> ContactInfoId { get; set; }
        public string Description { get; set; }
        public bool IsSeniorRestricted { get; set; }
        public string InternalName { get; set; }
        public Nullable<bool> HasOperatingHours { get; set; }
        public Nullable<bool> UseCustomPhoneNumbers { get; set; }
        public Nullable<System.DateTime> LastRefreshDateUtc { get; set; }
        public string WebsiteUrl { get; set; }
        public bool IsDeleted { get; set; }
        public string Directions { get; set; }
        public string CustomPhoneId { get; set; }
        public string CustomPhoneNumber { get; set; }
        public bool RecordCalls { get; set; }
        public Nullable<long> PropertyId { get; set; }
    
        public virtual ContactInfo ContactInfo { get; set; }
        public virtual ICollection<CommunityAmenity> CommunityAmenities { get; set; }
        public virtual ICollection<OperatingDay> OperatingDays { get; set; }
        public virtual ICollection<FeaturedCommunity> FeaturedCommunities { get; set; }
        public virtual ICollection<CommunityPhoto> CommunityPhotos { get; set; }
        public virtual Property Property { get; set; }
        public virtual ICollection<Building> Buildings { get; set; }
        public virtual User User { get; set; }
    }
}
