//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfo
    {
        public ContactInfo()
        {
            this.Communities = new HashSet<Community>();
            this.Buildings = new HashSet<Building>();
        }
    
        public int ContactInfoId { get; set; }
        public int UserId { get; set; }
        public int ContactInfoTypeCode { get; set; }
        public string Name { get; set; }
        public string CompanyName { get; set; }
        public string PhoneNumber { get; set; }
        public bool ShowPhoneNumber { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsAcceptTextMessages { get; set; }
    
        public virtual ICollection<Community> Communities { get; set; }
        public virtual ICollection<Building> Buildings { get; set; }
        public virtual User User { get; set; }
    }
}
