//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailPreference
    {
        public long EmailPreferenceId { get; set; }
        public int UserId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public bool IsNotifyMessages { get; set; }
        public bool IsNotifyApplications { get; set; }
        public int AnalyticReportFequency { get; set; }
        public Nullable<System.DateTime> AnalyticReportDateUtc { get; set; }
        public bool IsOpted { get; set; }
        public System.Guid OptOutKey { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime UpdateDateUtc { get; set; }
        public int PhoneLeadReportFrequency { get; set; }
        public Nullable<System.DateTime> PhoneLeadReportDateUtc { get; set; }
    
        public virtual User User { get; set; }
    }
}
