//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeaturedCommunity
    {
        public int FeaturedCommunityId { get; set; }
        public long CommunityId { get; set; }
        public System.DateTime ScheduledDate { get; set; }

        public Common.FeaturedCommunity ToFeaturedCommunity()
        {
            return new Common.FeaturedCommunity
            {
                FeaturedCommunityId = this.FeaturedCommunityId,
                CommunityId = this.CommunityId,
                ScheduledDate = this.ScheduledDate
            };
        }
        public virtual Community Community { get; set; }
    }
}
