//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormCategory
    {
        public FormCategory()
        {
            this.Forms = new HashSet<Form>();
        }
    
        public long FormCategoryId { get; set; }
        public string Name { get; set; }
        public int TypeCode { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime UpdateDateUtc { get; set; }
        public int Order { get; set; }
    
        public virtual ICollection<Form> Forms { get; set; }
    }
}
