//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public long FormId { get; set; }
        public long FormProviderId { get; set; }
        public long FormCategoryId { get; set; }
        public string State { get; set; }
        public string PreviewProviderId { get; set; }
        public string SmallThumbnailUrl { get; set; }
        public string LargeThumbnailUrl { get; set; }
        public bool IsOffline { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime UpdateDateUtc { get; set; }
    
        public virtual FormCategory FormCategory { get; set; }
        public virtual FormProvider FormProvider { get; set; }
    }
}
