//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestCard
    {
        public long GuestCardId { get; set; }
        public string ListingId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Comments { get; set; }
        public string MoveInDate { get; set; }
        public Nullable<int> Bedrooms { get; set; }
        public Nullable<float> Bathrooms { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
