//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalEntity
    {
        public LegalEntity()
        {
            this.MerchantAccounts = new HashSet<MerchantAccount>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string ResourceId { get; set; }
        public string ResourceUrl { get; set; }
        public string RentMoolaResourceId { get; set; }
        public string RentMoolaResourceUrl { get; set; }
        public int StatusCode { get; set; }
        public string SSNLast4 { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<MerchantAccount> MerchantAccounts { get; set; }
        public virtual User User { get; set; }
    }
}
