//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingReport
    {
        public long ListingReportId { get; set; }
        public long BuildingId { get; set; }
        public int ReportType { get; set; }
        public string Content { get; set; }
        public int Points { get; set; }
        public int ActionTakenType { get; set; }
    
        public virtual Building Building { get; set; }
    }
}
