//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalService
    {
        public LocalService()
        {
            this.LocalServiceZips = new HashSet<LocalServiceZip>();
        }
    
        public long LocalServiceId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string LogoUrl { get; set; }
    
        public virtual ICollection<LocalServiceZip> LocalServiceZips { get; set; }
    }
}
