//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantAccount
    {
        public MerchantAccount()
        {
            this.PaymentSeries = new HashSet<PaymentSeries>();
            this.Transfers = new HashSet<Transfer>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int LegalEntityId { get; set; }
        public string ACHResourceId { get; set; }
        public string Nickname { get; set; }
        public int AccountTypeCode { get; set; }
        public string AccountLast4 { get; set; }
        public Nullable<decimal> PaymentCapAmount { get; set; }
        public string RentMoolaCCResourceId { get; set; }
        public string RentMoolaACHResourceId { get; set; }
        public string RentMoolaCashResourceId { get; set; }
    
        public virtual LegalEntity LegalEntity { get; set; }
        public virtual ICollection<PaymentSeries> PaymentSeries { get; set; }
        public virtual ICollection<Transfer> Transfers { get; set; }
        public virtual User User { get; set; }
    }
}
