//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long MessageId { get; set; }
        public int ThreadId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Content { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public bool IsRemovedBySender { get; set; }
        public bool IsRemovedByRecipient { get; set; }
        public string SmsPhoneNumber { get; set; }
    
        public virtual Thread Thread { get; set; }
        public virtual User User { get; set; }
    }
}
