//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NextRecurringPayment
    {
        public long NextRecurringPaymentId { get; set; }
        public long RecurringPaymentId { get; set; }
        public long BuildingId { get; set; }
        public int LandlordBankAccountId { get; set; }
        public int TenantBankAccountId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime ProcessDate { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime UpdateDateUtc { get; set; }
        public Nullable<long> LandlordAchTransactionId { get; set; }
        public Nullable<long> TenantAchTransactionId { get; set; }
        public int StatusCode { get; set; }
    
        public virtual AchTransaction AchTransaction { get; set; }
        public virtual AchTransaction AchTransaction1 { get; set; }
        public virtual BankAccount BankAccount { get; set; }
        public virtual BankAccount BankAccount1 { get; set; }
        public virtual RecurringPayment RecurringPayment { get; set; }
        public virtual Building Building { get; set; }
    }
}
