//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ReferenceUserId { get; set; }
        public Nullable<long> BuildingId { get; set; }
        public int CategoryCode { get; set; }
        public bool IsCompleted { get; set; }
        public string Data { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsTenant { get; set; }
        public bool IsViewed { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
