//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int OrderItemId { get; set; }
        public int OrderId { get; set; }
        public int Quantity { get; set; }
        public string ProductId { get; set; }
        public string ProductOption { get; set; }
        public string ProductDescription { get; set; }
        public decimal Price { get; set; }

        public Common.OrderItem ToOrderItem()
        {
            Common.OrderItem orderItem = new Common.OrderItem
            {
                OrderItemId = this.OrderItemId,
                OrderId = this.OrderId,
                Quantity = this.Quantity,
                ProductId = this.ProductId,
                ProductOption = this.ProductOption,
                ProductDescription = this.ProductDescription,
                Price = this.Price
            };

            return orderItem;
        }

        public virtual Order Order { get; set; }

    }
}
