//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.Buildings = new HashSet<Building>();
            this.Screenings = new HashSet<Screening>();
        }
    
        public int OrderId { get; set; }
        public Nullable<long> BuildingId { get; set; }
        public int UserId { get; set; }
        public decimal OrderTotal { get; set; }
        public decimal OrderSubTotal { get; set; }
        public string PromoCodeId { get; set; }
        public Nullable<decimal> PromoDiscountTotal { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int OrderStatusCode { get; set; }
        public string CreatedBy { get; set; }
        public string CardId { get; set; }
        public Nullable<long> PropertyId { get; set; }
    
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual PromoCode PromoCode { get; set; }
        public virtual Property Property { get; set; }
        public virtual ICollection<Building> Buildings { get; set; }
        public virtual Building Building { get; set; }
        public virtual ICollection<Screening> Screenings { get; set; }
        public virtual User User { get; set; }
    }
}
