//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        public PaymentMethod()
        {
            this.AutopaySettings = new HashSet<AutopaySetting>();
            this.ScheduledTransactions = new HashSet<ScheduledTransaction>();
        }
    
        public long PaymentMethodId { get; set; }
        public int UserId { get; set; }
        public string ResourceId { get; set; }
        public string Name { get; set; }
        public int PaymentMethodTypeCode { get; set; }
        public string PaymentMethodLast4 { get; set; }
        public bool IsPrimary { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime UpdateDateUtc { get; set; }
        public Nullable<int> BankAccountTypeCode { get; set; }
        public string RentMoolaResourceId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<AutopaySetting> AutopaySettings { get; set; }
        public virtual ICollection<ScheduledTransaction> ScheduledTransactions { get; set; }
        public virtual User User { get; set; }
    }
}
