//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentInvite
    {
        public System.Guid PaymentInviteId { get; set; }
        public long BuildingId { get; set; }
        public int BankAccountId { get; set; }
        public decimal Amount { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public bool IsAccepted { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime UpdateDateUtc { get; set; }
        public long ConfirmationNumber { get; set; }
        public System.DateTime StartDateUtc { get; set; }
        public System.DateTime EndDateUtc { get; set; }
        public int DayDue { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual Building Building { get; set; }
    }
}
