//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentSeries
    {
        public PaymentSeries()
        {
            this.AutopaySettings = new HashSet<AutopaySetting>();
            this.Payments = new HashSet<Payment>();
            this.PaymentSeriesLineItems = new HashSet<PaymentSeriesLineItem>();
            this.ScheduledTransactions = new HashSet<ScheduledTransaction>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int PaymentSeriesId { get; set; }
        public decimal MonthlyAmount { get; set; }
        public int GracePeriod { get; set; }
        public bool ApplyLateFee { get; set; }
        public Nullable<decimal> LateFeeAmount { get; set; }
        public System.DateTime AgreeToTermsUtc { get; set; }
        public int MerchantAccountId { get; set; }
        public int LeaseId { get; set; }
        public int UserId { get; set; }
        public Nullable<decimal> PastDueAmount { get; set; }
        public Nullable<int> MonthsPastDue { get; set; }
        public int StatusCode { get; set; }
        public int MonthlyDueDay { get; set; }
        public System.DateTime FirstPaymentDateUtc { get; set; }
        public Nullable<System.DateTime> FinalPaymentDateUtc { get; set; }
        public bool IsFirstPaymentProrated { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime UpdateDateUtc { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<AutopaySetting> AutopaySettings { get; set; }
        public virtual Lease Lease { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<PaymentSeriesLineItem> PaymentSeriesLineItems { get; set; }
        public virtual ICollection<ScheduledTransaction> ScheduledTransactions { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual MerchantAccount MerchantAccount { get; set; }
        public virtual User User { get; set; }
    }
}
