//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public System.Guid PhotoId { get; set; }
        public long BuildingId { get; set; }
        public bool IsPrimary { get; set; }
        public int SortOrder { get; set; }
        public string Extension { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdateDateUtc { get; set; }
        public string UpdatedBy { get; set; }

        public Common.Listing.Photo ToPhoto()
        {
            return new Common.Listing.Photo
            {
                BuildingId = this.BuildingId,
                PhotoId = this.PhotoId,
                Extension = this.Extension,
                SortOrder = this.SortOrder,
                SmallPhoto = PhotoLink.GetPhotoLink(BuildingId, PhotoId, 50, 50, Extension),
                MediumPhoto = PhotoLink.GetPhotoLink(BuildingId, PhotoId, 200, 150, Extension),
                LargePhoto = PhotoLink.GetPhotoLink(BuildingId, PhotoId, 600, 395, Extension)
            };
        }

        public virtual Building Building { get; set; }
    }
}
