//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Press
    {
        public int PressId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int CategoryCode { get; set; }
        public string Slug { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime UpdateDateUtc { get; set; }
        public string ExternalUrl { get; set; }
        public bool IsDeleted { get; set; }
    }
}
