//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoCode
    {
        public PromoCode()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public string Code { get; set; }
        public int UserId { get; set; }
        public string Description { get; set; }
        public float Discount { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> MinimumOrderPrice { get; set; }
        public Nullable<int> UsesAvailable { get; set; }
        public System.DateTime StartDateUtc { get; set; }
        public System.DateTime EndDateUtc { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<decimal> MoneyLeft { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual User User { get; set; }
    }
}
