//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public Property()
        {
            this.Communities = new HashSet<Community>();
            this.Leases = new HashSet<Lease>();
            this.RentalApplications = new HashSet<RentalApplication>();
            this.Orders = new HashSet<Order>();
            this.Buildings = new HashSet<Building>();
            this.Screenings = new HashSet<Screening>();
        }
    
        public long PropertyId { get; set; }
        public int UserId { get; set; }
        public int PropertyTypeCode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string StreetHash { get; set; }
        public string FullHash { get; set; }
        public float Latitude { get; set; }
        public float Longitude { get; set; }
        public string ThumbnailUrl { get; set; }
        public bool IsApplicationsEnabled { get; set; }
        public bool IsScreeningRequired { get; set; }
        public Nullable<System.DateTime> ApplicationActivityDateUtc { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Community> Communities { get; set; }
        public virtual ICollection<Lease> Leases { get; set; }
        public virtual ICollection<RentalApplication> RentalApplications { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Building> Buildings { get; set; }
        public virtual ICollection<Screening> Screenings { get; set; }
        public virtual User User { get; set; }
    }
}
