//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecurringPayment
    {
        public RecurringPayment()
        {
            this.NextRecurringPayments = new HashSet<NextRecurringPayment>();
        }
    
        public long RecurringPaymentId { get; set; }
        public long BuildingId { get; set; }
        public int LandlordBankAccountId { get; set; }
        public int TenantBankAccountId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime StartDateUtc { get; set; }
        public System.DateTime EndDateUtc { get; set; }
        public int ProcessDay { get; set; }
        public int StatusCode { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime UpdateDateUtc { get; set; }
        public bool TenantIsDismissed { get; set; }
        public bool LandlordIsDismissed { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual BankAccount BankAccount1 { get; set; }
        public virtual ICollection<NextRecurringPayment> NextRecurringPayments { get; set; }
        public virtual Building Building { get; set; }
    }
}
