//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalApplication
    {
        public RentalApplication()
        {
            this.RentalApplicationUsers = new HashSet<RentalApplicationUser>();
            this.RentalApplicants = new HashSet<RentalApplicant>();
        }
    
        public long RentalApplicationId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<long> BuildingId { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public int StatusCode { get; set; }
        public string StatusText { get; set; }
        public Nullable<System.DateTime> SubmitDateUtc { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime UpdateDateUtc { get; set; }
        public bool IsDismissed { get; set; }
        public bool IsArchived { get; set; }
        public bool WasInvited { get; set; }
        public bool IsApplicationRequired { get; set; }
        public decimal RentAmount { get; set; }
    
        public virtual ICollection<RentalApplicationUser> RentalApplicationUsers { get; set; }
        public virtual Property Property { get; set; }
        public virtual Building Building { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<RentalApplicant> RentalApplicants { get; set; }
    }
}
