//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screening
    {
        public long ScreeningId { get; set; }
        public Nullable<long> RentalApplicationUserId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<long> BuildingId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public bool IsPrepaid { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public string BackgroundProviderId { get; set; }
        public string BackgroundProviderStatus { get; set; }
        public string CreditProviderId { get; set; }
        public string CreditProviderShareId { get; set; }
        public string CreditProviderStatus { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime UpdateDateUtc { get; set; }
        public long RentalApplicantId { get; set; }
        public long PropertyId { get; set; }
        public int StatusCode { get; set; }
        public Nullable<System.DateTime> SubmitDateUtc { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Property Property { get; set; }
        public virtual RentalApplicationUser RentalApplicationUser { get; set; }
        public virtual User User { get; set; }
        public virtual RentalApplicant RentalApplicant { get; set; }
    }
}
