//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantApplication
    {
        public int TenantApplicationId { get; set; }
        public int TenantUserId { get; set; }
        public long BuildingId { get; set; }
        public Nullable<System.DateTime> CreditRequestDateUtc { get; set; }
        public string CreditResult { get; set; }
        public Nullable<System.DateTime> BackgroundRequestDateUtc { get; set; }
        public string BackgroundResult { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime UpdateDateUtc { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual User User { get; set; }
    }
}
