//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public Tenant()
        {
            this.AutopaySettings = new HashSet<AutopaySetting>();
            this.ScheduledTransactions = new HashSet<ScheduledTransaction>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int TenantId { get; set; }
        public int LeaseId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int StatusCode { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid InviteKey { get; set; }
    
        public virtual ICollection<AutopaySetting> AutopaySettings { get; set; }
        public virtual Lease Lease { get; set; }
        public virtual ICollection<ScheduledTransaction> ScheduledTransactions { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual User User { get; set; }
    }
}
