//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thread
    {
        public Thread()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public int ThreadId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int UserId2 { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public Nullable<int> User1Type { get; set; }
        public Nullable<int> User2Type { get; set; }
        public Nullable<long> BuildingId { get; set; }
        public string SmsPhoneNumber { get; set; }
        public Nullable<System.Guid> SmsReplyEmailKey { get; set; }
        public Nullable<System.DateTime> UpdateDateUtc { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
        public virtual Building Building { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
