//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.ScheduledTransactions = new HashSet<ScheduledTransaction>();
        }
    
        public long TransactionId { get; set; }
        public Nullable<int> PaymentSeriesId { get; set; }
        public Nullable<int> TenantId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransactionDateUtc { get; set; }
        public int StatusCode { get; set; }
        public string CommerceKey { get; set; }
        public int PaymentTypeCode { get; set; }
        public string StatusMessage { get; set; }
        public string Description { get; set; }
        public Nullable<long> PaymentMethodId { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime UpdateDateUtc { get; set; }
        public decimal Fee { get; set; }
        public Nullable<long> TransferId { get; set; }
        public Nullable<long> OriginalTransactionId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsPending { get; set; }
        public string PendingReason { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual PaymentSeries PaymentSeries { get; set; }
        public virtual ICollection<ScheduledTransaction> ScheduledTransactions { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual Transfer Transfer { get; set; }
    }
}
