//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public Transfer()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public long TransferId { get; set; }
        public int MerchantAccountId { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransferDateUtc { get; set; }
        public decimal Total { get; set; }
        public string RentMoolaRefNumber { get; set; }
        public string RentMoolaResourceId { get; set; }
        public string RentMoolaAccountResourceId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime UpdateDateUtc { get; set; }
        public string ResourceId { get; set; }
        public string AccountResourceId { get; set; }
        public string DestinationPaymentResourceId { get; set; }
        public Nullable<long> PayoutId { get; set; }
    
        public virtual MerchantAccount MerchantAccount { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual User User { get; set; }
    }
}
