//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentler.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Applicants = new HashSet<Applicant>();
            this.Applications = new HashSet<Application>();
            this.ApplicationUsers = new HashSet<ApplicationUser>();
            this.ApplicationUsers1 = new HashSet<ApplicationUser>();
            this.Articles = new HashSet<Article>();
            this.BankAccounts = new HashSet<BankAccount>();
            this.Buildings = new HashSet<Building>();
            this.Communities = new HashSet<Community>();
            this.ContactInfoes = new HashSet<ContactInfo>();
            this.EmailPreferences = new HashSet<EmailPreference>();
            this.LegalEntities = new HashSet<LegalEntity>();
            this.MerchantAccounts = new HashSet<MerchantAccount>();
            this.Messages = new HashSet<Message>();
            this.Notifications = new HashSet<Notification>();
            this.Notifications1 = new HashSet<Notification>();
            this.OldUserPasswords = new HashSet<OldUserPassword>();
            this.Orders = new HashSet<Order>();
            this.PaymentMethods = new HashSet<PaymentMethod>();
            this.PaymentSeries = new HashSet<PaymentSeries>();
            this.PromoCodes = new HashSet<PromoCode>();
            this.Properties = new HashSet<Property>();
            this.RentalApplications = new HashSet<RentalApplication>();
            this.RentalApplicationUsers = new HashSet<RentalApplicationUser>();
            this.RentalApplicationUsers1 = new HashSet<RentalApplicationUser>();
            this.SavedBuildings = new HashSet<SavedBuilding>();
            this.Screenings = new HashSet<Screening>();
            this.TenantApplications = new HashSet<TenantApplication>();
            this.Tenants = new HashSet<Tenant>();
            this.Threads = new HashSet<Thread>();
            this.Threads1 = new HashSet<Thread>();
            this.Transfers = new HashSet<Transfer>();
            this.UserNotes = new HashSet<UserNote>();
            this.Verifications = new HashSet<Verification>();
            this.Roles = new HashSet<Role>();
            this.RentalApplicants = new HashSet<RentalApplicant>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime UpdateDateUtc { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid ReferenceId { get; set; }
        public bool IsVerified { get; set; }
        public string StripeCustomerId { get; set; }
        public string StripeOrderCustomerId { get; set; }
        public string ApplicationId { get; set; }
        public string Phone { get; set; }
        public string Introduction { get; set; }
        public string AvatarUri { get; set; }
        public Nullable<int> VerifyCount { get; set; }
        public Nullable<System.DateTime> LockoutUpdateDateUtc { get; set; }
        public Nullable<int> RefreshDays { get; set; }
        public Nullable<System.DateTime> LastRefreshDateUtc { get; set; }
        public Nullable<int> FailedPasswordAttempts { get; set; }
        public Nullable<bool> IsLockedOut { get; set; }
        public Nullable<System.DateTime> LockedOutDateUtc { get; set; }
        public int AdvertisedListingCount { get; set; }
        public int UpgradeStatus { get; set; }
        public string RequestedPackage { get; set; }
        public string InvoiceContactName { get; set; }
        public string InvoiceContactPhone { get; set; }
        public bool CanAccessForms { get; set; }
        public string UserResourceId { get; set; }
    
        public virtual AffiliateUser AffiliateUser { get; set; }
        public virtual ICollection<Applicant> Applicants { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<ApplicationUser> ApplicationUsers { get; set; }
        public virtual ICollection<ApplicationUser> ApplicationUsers1 { get; set; }
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<BankAccount> BankAccounts { get; set; }
        public virtual ICollection<Building> Buildings { get; set; }
        public virtual ICollection<Community> Communities { get; set; }
        public virtual ICollection<ContactInfo> ContactInfoes { get; set; }
        public virtual ICollection<EmailPreference> EmailPreferences { get; set; }
        public virtual ICollection<LegalEntity> LegalEntities { get; set; }
        public virtual ICollection<MerchantAccount> MerchantAccounts { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Notification> Notifications1 { get; set; }
        public virtual ICollection<OldUserPassword> OldUserPasswords { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<PaymentMethod> PaymentMethods { get; set; }
        public virtual ICollection<PaymentSeries> PaymentSeries { get; set; }
        public virtual ICollection<PromoCode> PromoCodes { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
        public virtual ICollection<RentalApplication> RentalApplications { get; set; }
        public virtual ICollection<RentalApplicationUser> RentalApplicationUsers { get; set; }
        public virtual ICollection<RentalApplicationUser> RentalApplicationUsers1 { get; set; }
        public virtual ICollection<SavedBuilding> SavedBuildings { get; set; }
        public virtual Scammer Scammer { get; set; }
        public virtual ICollection<Screening> Screenings { get; set; }
        public virtual ICollection<TenantApplication> TenantApplications { get; set; }
        public virtual ICollection<Tenant> Tenants { get; set; }
        public virtual ICollection<Thread> Threads { get; set; }
        public virtual ICollection<Thread> Threads1 { get; set; }
        public virtual ICollection<Transfer> Transfers { get; set; }
        public virtual ICollection<UserNote> UserNotes { get; set; }
        public virtual UserSetting UserSetting { get; set; }
        public virtual ICollection<Verification> Verifications { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<RentalApplicant> RentalApplicants { get; set; }
    }
}
